# Contrôles négatifs {#NegativeControlsAppendix}

Cette annexe contient des contrôles négatifs utilisés dans divers chapitres du livre.


## ACEi et THZ {#AceiThzNsc}

Tableau: (\#tab:AceiThzNsc) Résultats des contrôles négatifs lors de la comparaison des inhibiteurs de l'ECA (ACEi) aux diurétiques thiazidiques et analogues thiazidiques (THZ).

| Concept ID | Nom du concept                                             |
| ----------:|:---------------------------------------------------------- |
| 434165 | Frottis cervical anormal |
| 436409 | Pupille anormale |
| 199192 | Abrasion et/ou brûlure par friction du tronc sans infection |
| 4088290 | Absence de sein |
| 4092879 | Rein absent |
| 44783954 | Reflux acide |
| 75911 | Hallux valgus acquis |
| 137951 | Kératodermie acquise |
| 77965 | Doigt à ressort acquis |
| 376707 | Conjonctivite aiguë |
| 4103640 | Pied amputé |
| 73241 | Polype anal et rectal |
| 133655 | Brûlure de l’avant-bras |
| 73560 | Éperon calcanéen |
| 434327 | Abus de cannabis |
| 4213540 | Dysfonction somatique cervicale |
| 140842 | Changements dans la texture de la peau |
| 81378 | Chondromalacie de la rotule |
| 432303 | Abus de cocaïne |
| 4201390 | Présence de colostomie |
| 46269889 | Complication due à la maladie de Crohn |
| 134438 | Dermatite de contact |
| 78619 | Contusion du genou |
| 201606 | Maladie de Crohn |
| 76786 | Derangement du genou |
| 4115402 | Difficulté à dormir |
| 45757370 | Disproportion du sein reconstruit |
| 433111 | Effets de la faim |
| 433527 | Endométriose |
| 4170770 | Kyste épidermoïde |
| 4092896 | Contenu des selles anormal |
| 259995 | Corps étranger dans un orifice |
| 40481632 | Kyste ganglionnaire |
| 4166231 | Prédisposition génétique |
| 433577 | Orteils en marteau |
| 4231770 | Thrombophilie héréditaire |
| 440329 | Zona sans complication |
| 4012570 | Comportement sexuel à haut risque |
| 4012934 | Homocystinurie |
| 441788 | Infection par le papillomavirus humain |
| 4201717 | Présence d’iléostomie |
| 374375 | Cérumen impacté |
| 4344500 | Syndrome d'impact de la région de l'épaule |
| 139099 | Ongle incarné |
| 444132 | Blessure du genou |
| 196168 | Régles irrégulières |
| 432593 | Kwashiorkor |
| 434203 | Suite tardive d’une contusion |
| 438329 | Suite tardive d’un accident de la route |
| 195873 | Leucorrhée |
| 4083487 | Druses maculaires |
| 4103703 | Méléna |
| 4209423 | Dépendance à la nicotine |
| 377572 | Effets du bruit sur l’oreille interne |
| 40480893 | Réaction tuberculinique non spécifique |
| 136368 | Goitre multinodulaire non toxique |
| 140648 | Onychomycose due à des dermatophytes |
| 438130 | Abus d’opioïdes |
| 4091513 | Passage de gaz |
| 4202045 | Syndrome de fatigue postvirale |
| 373478 | Presbytie |
| 46286594 | Problème lié au mode de vie |
| 439790 | Psychalgie |
| 81634 | Sein ptosé |
| 380706 | Astigmatisme régulier |
| 141932 | Hyperkératose sénile |
| 36713918 | Dysfonction somatique de la région lombaire |
| 443172 | Écharde du visage, sans grande plaie ouverte |
| 81151 | Entorse de la cheville |
| 72748 | Entorse de la capsule rotatrice |
| 378427 | Insuffisance du film lacrymal |
| 437264 | Syndrome de dépendance au tabac |
| 194083 | Vaginite et vulvovaginite |
| 140641 | Verrue vulgaire |
| 440193 | Mains tombantes |
| 4115367 | Douleur à l’articulation du poignet |
