## # Modèle de protocole {#ProtocolTemplate}

1. Table des matières
2. Liste des abréviations
3. Résumé
4. Amendements et mises à jour
5. Jalons
6. Raisons et contexte
7. Objectifs de l'étude
    - Hypothèses principales
    - Hypothèses secondaires
    - Objectifs principaux
    - Objectifs secondaires
8. Méthodes de recherche
    - Plan d'étude
    - Source(s) de données
    - Population d'étude
    - Expositions
    - Résultats
    - Covariables
9. Plan d'analyse de données
    - Calcul du temps à risque
    - Spécification du modèle
    - Agrégation des estimations d'effet à travers les bases de données
    - Analyses à réaliser
    - Production
    - Évaluation des preuves
10. Diagnostics de l'étude
    - Taille de l'échantillon et puissance de l'étude
    - Comparabilité des cohortes
    - Évaluation des erreurs systématiques
11.	Atouts et limites des méthodes de recherche
12.	Protection des sujets humains
13.	Gestion et rapport des événements indésirables et des réactions indésirables
14.	Plans de diffusion et de communication des résultats de l'étude
15.	Annexe : Contrôles négatifs
16.	Références

## NA
